### ISSUE TITLE
你好，请问这个问题是什么引起的啊！

### ISSUE THREAD

**Issue by shineforever** [lzjun567/django_blog#16]
你好，我的python版本：2.7.9，django版本：1.8.2，执行“python manage.py syncdb”包如下错误：
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/pyenv/versions/2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/pyenv/versions/2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/local/pyenv/versions/2.7.9/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/pyenv/versions/2.7.9/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/pyenv/versions/2.7.9/lib/python2.7/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/usr/local/pyenv/versions/2.7.9/lib/python2.7/site-packages/debug_toolbar/settings.py", line 237, in patch_all
    patch_middleware_classes()
  File "/usr/local/pyenv/versions/2.7.9/lib/python2.7/site-packages/debug_toolbar/settings.py", line 216, in patch_middleware_classes
    if not is_toolbar_middleware_installed():
  File "/usr/local/pyenv/versions/2.7.9/lib/python2.7/site-packages/debug_toolbar/settings.py", line 196, in is_toolbar_middleware_installed
    from debug_toolbar.middleware import DebugToolbarMiddleware
  File "/usr/local/pyenv/versions/2.7.9/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 17, in <module>
    from debug_toolbar.toolbar import DebugToolbar
  File "/usr/local/pyenv/versions/2.7.9/lib/python2.7/site-packages/debug_toolbar/toolbar.py", line 167, in <module>
    urlpatterns = DebugToolbar.get_urls()
  File "/usr/local/pyenv/versions/2.7.9/lib/python2.7/site-packages/debug_toolbar/toolbar.py", line 161, in get_urls
    for panel_class in cls.get_panel_classes():
  File "/usr/local/pyenv/versions/2.7.9/lib/python2.7/site-packages/debug_toolbar/toolbar.py", line 138, in get_panel_classes
    (panel_module, e))
django.core.exceptions.ImproperlyConfigured: Error importing debug panel debug_toolbar.panels.templates: "cannot import name get_standard_processors"

pip相关的包已经安装了！

**Comment by lzjun567** [comment]
是你用django的版本太高，django-debug-toolbar1.2.2不兼容django1.8.2

解决的方法是把django-debug-toolbar升级到1.3.2

**Comment by shineforever** [comment]
谢谢，正如你所说的！





在 2015-08-21 16:22:01，"liuzhijun" <notifications@github.com> 写道：


是你用django的版本太高，django-debug-toolbar1.2.2不兼容django1.8.2

解决的方法是把django-debug-toolbar升级到1.3.2
