### ISSUE TITLE
AttributeError: 'module' object has no attribute 'QuerySet'

### ISSUE THREAD

**Issue by Profeel** [lzjun567/django_blog#19]
syncdb的时候出现错误
```
(django_blog)[root@dbp django_blog]# python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/django_blog/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/root/django_blog/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/django_blog/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/root/django_blog/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/root/django_blog/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/root/django_blog/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/root/django_blog/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/root/django_blog/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/root/django_blog/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/root/django_blog/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/root/django_blog/lib/python2.7/site-packages/reversion/models.py", line 116, in <module>
```

**Comment by eltonlau1994** [comment]
I think it is because you are using Python 2.7 instead of 3.4.x ?
but I got a problem in syncdb as well.

**Comment by Profeel** [comment]
@eltonlau1994 I'm using 2.7，but I haven't try 3.4.x,I will try for a later
