### ISSUE TITLE
按照说明进行配置后，出现下面错误，球解答

### ISSUE THREAD

**Issue by xiyanxiyan10** [lzjun567/django_blog#20]
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/debug_toolbar/settings.py", line 237, in patch_all
    patch_middleware_classes()
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/debug_toolbar/settings.py", line 216, in patch_middleware_classes
    if not is_toolbar_middleware_installed():
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/debug_toolbar/settings.py", line 196, in is_toolbar_middleware_installed
    from debug_toolbar.middleware import DebugToolbarMiddleware
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/debug_toolbar/middleware.py", line 17, in <module>
    from debug_toolbar.toolbar import DebugToolbar
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/debug_toolbar/toolbar.py", line 167, in <module>
    urlpatterns = DebugToolbar.get_urls()
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/debug_toolbar/toolbar.py", line 161, in get_urls
    for panel_class in cls.get_panel_classes():
  File "/home/ubuntu/.virtualenvs/django_blog/lib/python3.4/site-packages/debug_toolbar/toolbar.py", line 138, in get_panel_classes
    (panel_module, e))
django.core.exceptions.ImproperlyConfigured: Error importing debug panel debug_toolbar.panels.templates: "cannot import name 'get_standard_processors'"

**Comment by lzjun567** [comment]
应该是debug_toolbar和当前的django 版本不兼容

**Comment by xiyanxiyan10** [comment]
debug_toolbar安装哪个版本的好点哟，我是使用dev.txt的依赖安装的

**Comment by xiyanxiyan10** [comment]
谢谢，解决啦，
这个版本工作正常，建议更新下README  
Downloading django_debug_toolbar-1.4-py2.py3-none-any.whl

**Comment by lzjun567** [comment]
thanks，代码已经更新
